GET http://localhost:3088
###
GET http://localhost:3088/ping
###
GET http://localhost:3088/app/v1/admin
###
GET http://localhost:3088/app/v1/healthz
###

GET http://localhost:3088/app/v1/healthcheck
###
GET http://localhost:3088/app/v1/dnscheck
###
POST http://localhost:3088/app/v1/signup
content-type: application/json

{
"Id" : "5",
"Title" : "Electronics",
"Content" : "Technical",
"Summary" : "How to make circuit"
}
###
POST http://localhost:3088/app/v1/set-env
content-type: application/json

{
"envName" : "ENV_NAME_GO_TEST",
"envValue" : "workingusingGO"
}
###
POST http://localhost:3088/app/v1/create-profile
content-type: application/json

{
"name" : "Jay",
"city" : "Bellevue"
}
###

POST http://localhost:3088/app/v1/login
Content-Type: application/x-www-form-urlencoded

username=Jay
&password=pass12
